<a href="https://colab.research.google.com/github/KShikha19/PY/blob/main/Pandas4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
!gdown 1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm

Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 49.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 58.1MB/s]

In [ ]:
import pandas as pd
import numpy as np

movies = pd.read_csv('movies.csv', index_col=0)
directors = pd.read_csv('directors.csv', index_col=0)

data = movies.merge(directors, how='left', left_on='director_id',right_on='id')
data.drop(['director_id','id_y'],axis=1,inplace=True)

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
#tell me the movies directed by high budget directors
#most productive directors
#most risky movies

In [ ]:
#high budget directors => movies

In [ ]:
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male

In [ ]:
#find the details of all the movies directed by high budget directors
#high budget => atleast 1 movie with budget > 100M

In [ ]:
data['budget'] > 100000000

0        True
1        True
2        True
3        True
4        True
        ...
1460    False
1461    False
1462    False
1463    False
1464    False
Name: budget, Length: 1465, dtype: bool

In [ ]:
data[data['budget'] > 100000000] #masking

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
185,43897,105000000,58,121214377,Starship Troopers,6.7,1560,1997,Nov,Thursday,Paul Verhoeven,Male
186,43898,102000000,73,130482868,Cloud Atlas,6.6,2977,2012,Oct,Friday,Tom Tykwer,Male
201,43929,115000000,41,274703340,Lara Croft: Tomb Raider,5.7,2192,2001,Jun,Monday,Simon West,Male
290,44088,130000000,50,117831631,Pompeii,5.2,1267,2014,Feb,Tuesday,Paul W.S. Anderson,Male
328,44162,150000000,47,919838758,Shrek 2,6.7,2988,2004,May,Wednesday,Andrew Adamson,Male

In [ ]:
dir_max_budget = data.groupby('director_name')['budget'].max()

In [ ]:
dir_max_budget

director_name
Adam McKay                     100000000
Adam Shankman                   80000000
Alejandro González Iñárritu    135000000
Alex Proyas                    140000000
Alexander Payne                 30000000
                                 ...
Wes Craven                      40000000
Wolfgang Petersen              175000000
Woody Allen                     30000000
Zack Snyder                    250000000
Zhang Yimou                     94000000
Name: budget, Length: 199, dtype: int64

In [ ]:
dir_max_budget > 100000000

director_name
Adam McKay                     False
Adam Shankman                  False
Alejandro González Iñárritu     True
Alex Proyas                     True
Alexander Payne                False
                               ...
Wes Craven                     False
Wolfgang Petersen               True
Woody Allen                    False
Zack Snyder                     True
Zhang Yimou                    False
Name: budget, Length: 199, dtype: bool

In [ ]:
dir_max_budget[dir_max_budget > 100000000]

director_name
Alejandro González Iñárritu    135000000
Alex Proyas                    140000000
Andrew Adamson                 225000000
Ang Lee                        137000000
Barry Sonnenfeld               225000000
                                 ...
Tim Story                      130000000
Tom Shadyac                    175000000
Tom Tykwer                     102000000
Wolfgang Petersen              175000000
Zack Snyder                    250000000
Name: budget, Length: 79, dtype: int64

In [ ]:
names = dir_max_budget[dir_max_budget > 100000000].index

In [ ]:
dir_max_budget[dir_max_budget > 100000000].values

array([135000000, 140000000, 225000000, 137000000, 225000000, 120000000,
       210000000, 270000000, 125000000, 180000000, 250000000, 125000000,
       175000000, 150000000, 178000000, 140000000, 160000000, 110000000,
       150000000, 300000000, 180000000, 125000000, 237000000, 120000000,
       190000000, 160000000, 150000000, 125000000, 160000000, 125000000,
       200000000, 130000000, 150000000, 150000000, 185000000, 150000000,
       175000000, 140000000, 176000003, 150000000, 150000000, 200000000,
       200000000, 170000000, 200000000, 155000000, 210000000, 107000000,
       150000000, 155000000, 120000000, 105000000, 130000000, 209000000,
       250000000, 110000000, 110000000, 140000000, 200000000, 145000000,
       380000000, 145000000, 130000000, 200000000, 116000000, 200000000,
       150000000, 245000000, 258000000, 150000000, 115000000, 110000000,
       185000000, 200000000, 130000000, 175000000, 102000000, 175000000,
       250000000])

In [ ]:
df_budget = dir_max_budget[dir_max_budget > 100000000].reset_index()

In [ ]:
df_budget #try to perform join on this df and data to get the movies details

                  director_name     budget
0   Alejandro González Iñárritu  135000000
1                   Alex Proyas  140000000
2                Andrew Adamson  225000000
3                       Ang Lee  137000000
4              Barry Sonnenfeld  225000000
..                          ...        ...
74                    Tim Story  130000000
75                  Tom Shadyac  175000000
76                   Tom Tykwer  102000000
77            Wolfgang Petersen  175000000
78                  Zack Snyder  250000000

[79 rows x 2 columns]

In [ ]:
df_budget['director_name']

0     Alejandro González Iñárritu
1                     Alex Proyas
2                  Andrew Adamson
3                         Ang Lee
4                Barry Sonnenfeld
                 ...
74                      Tim Story
75                    Tom Shadyac
76                     Tom Tykwer
77              Wolfgang Petersen
78                    Zack Snyder
Name: director_name, Length: 79, dtype: object

In [ ]:
names #high budget directors names

Index(['Alejandro González Iñárritu', 'Alex Proyas', 'Andrew Adamson',
       'Ang Lee', 'Barry Sonnenfeld', 'Bill Condon', 'Brett Ratner',
       'Bryan Singer', 'Chris Columbus', 'Chris Weitz', 'Christopher Nolan',
       'Darren Aronofsky', 'David Ayer', 'David Fincher', 'Doug Liman',
       'Edward Zwick', 'Francis Lawrence', 'Frank Coraci', 'George Miller',
       'Gore Verbinski', 'Guillermo del Toro', 'Guy Ritchie', 'James Cameron',
       'James Mangold', 'James Wan', 'Jan de Bont', 'Joe Wright',
       'Joel Schumacher', 'John McTiernan', 'John Woo', 'Jon Favreau',
       'Jon M. Chu', 'Jon Turteltaub', 'Jonathan Liebesman', 'Justin Lin',
       'Kenneth Branagh', 'Kevin Reynolds', 'Lee Tamahori', 'Lilly Wachowski',
       'Louis Leterrier', 'M. Night Shyamalan', 'Marc Forster',
       'Martin Campbell', 'Martin Scorsese', 'McG', 'Michael Apted',
       'Michael Bay', 'Michael Mann', 'Mike Newell', 'Oliver Stone',
       'Paul Greengrass', 'Paul Verhoeven', 'Paul W.S. Anderson', 'Peter Berg',
       'Peter Jackson', 'Phillip Noyce', 'Raja Gosnell', 'Richard Donner',
       'Ridley Scott', 'Rob Cohen', 'Rob Marshall', 'Rob Minkoff',
       'Robert Schwentke', 'Robert Zemeckis', 'Roger Donaldson',
       'Roland Emmerich', 'Ron Howard', 'Sam Mendes', 'Sam Raimi',
       'Shawn Levy', 'Simon West', 'Steven Soderbergh', 'Steven Spielberg',
       'Tim Burton', 'Tim Story', 'Tom Shadyac', 'Tom Tykwer',
       'Wolfgang Petersen', 'Zack Snyder'],
      dtype='object', name='director_name')

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data['director_name'].isin(names)

0        True
1        True
2        True
3        True
4        True
        ...
1460     True
1461    False
1462    False
1463    False
1464    False
Name: director_name, Length: 1465, dtype: bool

In [ ]:
data[data['director_name'].isin(names)]['title']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                   Spider-Man 3
                          ...
1450                                     Mad Max
1451                                    Swingers
1452                                       Three
1458                                          Pi
1460                              The Last Waltz
Name: title, Length: 636, dtype: object

In [ ]:
#smarter ? => reduce the number of steps
def high_budget(g):
  return g['budget'].max() > 100000000 #79 groups

In [ ]:
data.groupby('director_name').filter(high_budget)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1450,48267,400000,33,100000000,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,Male
1451,48268,200000,13,4505922,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,Male
1452,48274,0,5,2611555,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,Male
1458,48335,60000,27,3221152,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male

In [ ]:
#using lambda in single line
data.groupby('director_name').filter(lambda g:g['budget'].max()>100000000)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1450,48267,400000,33,100000000,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,Male
1451,48268,200000,13,4505922,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,Male
1452,48274,0,5,2611555,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,Male
1458,48335,60000,27,3221152,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male

In [ ]:
#high risk movies
#if a movie has higher budget than avg revenue for that director => high risk movies

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data['budget'].mean()

np.float64(48022946.87986348)

In [ ]:
data['revenue'].mean()

np.float64(143253923.0750853)

In [ ]:
def risky(x):
  x['risky'] = x['budget'] - x['revenue'].mean() > 0
  return x

In [ ]:
data.groupby('director_name').apply(risky)

<ipython-input-45-547b10dbd5ed>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data.groupby('director_name').apply(risky)

                     id_x     budget  popularity    revenue  \
director_name
Adam McKay    176   43882  100000000          24  170432927
              323   44151   72500000          12  162966177
              366   44236   65000000          22  128107642
              505   44503   50000000          38  173649015
              839   45301   28000000          57  133346506
...                   ...        ...         ...        ...
Zhang Yimou   590   44692        110           9          0
              604   44733   31000000          23  177394432
              1217  46460          0          21   92863945
              1223  46493          0           1          0
              1389  47489          0           6          0

                                                          title  vote_average  \
director_name
Adam McKay    176                                The Other Guys           6.1
              323   Talladega Nights: The Ballad of Ricky Bobby           6.2
              366                                 Step Brothers           6.5
              505             Anchorman 2: The Legend Continues           6.0
              839                                 The Big Short           7.3
...                                                         ...           ...
Zhang Yimou   590                    Curse of the Golden Flower           6.6
              604                                          Hero           7.2
              1217                      House of Flying Daggers           7.1
              1223             A Woman, a Gun and a Noodle Shop           4.8
              1389                                  Coming Home           6.9

                    vote_count  year month        day director_name gender  \
director_name
Adam McKay    176         1383  2010   Aug     Friday    Adam McKay   Male
              323          491  2006   Aug     Friday    Adam McKay   Male
              366         1062  2008   Jul     Friday    Adam McKay   Male
              505          923  2013   Dec  Wednesday    Adam McKay   Male
              839         2607  2015   Dec     Friday    Adam McKay   Male
...                        ...   ...   ...        ...           ...    ...
Zhang Yimou   590          203  2006   Dec   Thursday   Zhang Yimou   Male
              604          635  2002   Dec   Thursday   Zhang Yimou   Male
              1217         439  2004   May  Wednesday   Zhang Yimou   Male
              1223          13  2009   Dec     Friday   Zhang Yimou   Male
              1389          49  2014   May     Friday   Zhang Yimou   Male

                    risky
director_name
Adam McKay    176   False
              323   False
              366   False
              505   False
              839   False
...                   ...
Zhang Yimou   590   False
              604   False
              1217  False
              1223  False
              1389  False

[1465 rows x 13 columns]

In [ ]:
data_risky = data.groupby('director_name',group_keys=False).apply(risky)

<ipython-input-46-20248bae7463>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_risky = data.groupby('director_name',group_keys=False).apply(risky)

In [ ]:
data_risky

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,risky
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,False
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male,False
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male,False
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male,False
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male,False
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male,False
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male,False
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male,False
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN,False

In [ ]:
data_risky['risky'].value_counts()

risky
False    1334
True      131
Name: count, dtype: int64

In [ ]:
data_risky['risky']

0       False
1       False
2       False
3       False
4       False
        ...
1460    False
1461    False
1462    False
1463    False
1464    False
Name: risky, Length: 1465, dtype: bool

In [ ]:
#masking
data_risky[data_risky['risky'] == True]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,risky
7,43608,200000000,107,586090727,Quantum of Solace,6.1,2965,2008,Oct,Thursday,Marc Forster,Male,True
12,43614,380000000,135,1045713802,Pirates of the Caribbean: On Stranger Tides,6.4,4948,2011,May,Saturday,Rob Marshall,Male,True
15,43618,200000000,37,310669540,Robin Hood,6.2,1398,2010,May,Wednesday,Ridley Scott,Male,True
20,43624,209000000,64,303025485,Battleship,5.5,2114,2012,Apr,Wednesday,Peter Berg,Male,True
24,43630,210000000,3,459359555,X-Men: The Last Stand,6.3,3525,2006,May,Wednesday,Brett Ratner,Male,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1347,47224,5000000,7,3263585,The Sweet Hereafter,6.8,103,1997,May,Wednesday,Atom Egoyan,Male,True
1349,47229,5000000,3,4842699,90 Minutes in Heaven,5.4,40,2015,Sep,Friday,Michael Polish,Male,True
1351,47233,5000000,6,0,Light Sleeper,5.7,15,1992,Aug,Friday,Paul Schrader,NaN,True
1356,47263,15000000,10,0,Dying of the Light,4.5,118,2014,Dec,Thursday,Paul Schrader,NaN,True
1383,47453,3500000,4,0,In the Name of the King III,3.3,19,2013,Dec,Friday,Uwe Boll,Male,True

#most productive directors

In [ ]:
#more work(more movies) => more productive

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data['director_name'].value_counts()

director_name
Steven Spielberg       26
Martin Scorsese        19
Clint Eastwood         19
Woody Allen            18
Spike Lee              16
                       ..
Mike Leigh              5
Brad Anderson           5
Michael Polish          5
Darren Lynn Bousman     5
Nicole Holofcener       5
Name: count, Length: 199, dtype: int64

In [ ]:
data_agg = data.groupby('director_name').aggregate({'year':['min','max'],'title':['count']})

In [ ]:
data_agg #multi level index

                             year       title
                              min   max count
director_name
Adam McKay                   2004  2015     6
Adam Shankman                2001  2012     8
Alejandro González Iñárritu  2000  2015     6
Alex Proyas                  1994  2016     5
Alexander Payne              1999  2013     5
...                           ...   ...   ...
Wes Craven                   1984  2011    10
Wolfgang Petersen            1981  2006     7
Woody Allen                  1977  2013    18
Zack Snyder                  2004  2016     7
Zhang Yimou                  2002  2014     6

[199 rows x 3 columns]

In [ ]:
data_agg.columns

MultiIndex([( 'year',   'min'),
            ( 'year',   'max'),
            ('title', 'count')],
           )

In [ ]:
data_agg['year']

                              min   max
director_name
Adam McKay                   2004  2015
Adam Shankman                2001  2012
Alejandro González Iñárritu  2000  2015
Alex Proyas                  1994  2016
Alexander Payne              1999  2013
...                           ...   ...
Wes Craven                   1984  2011
Wolfgang Petersen            1981  2006
Woody Allen                  1977  2013
Zack Snyder                  2004  2016
Zhang Yimou                  2002  2014

[199 rows x 2 columns]

In [ ]:
data_agg['year']['max']

director_name
Adam McKay                     2015
Adam Shankman                  2012
Alejandro González Iñárritu    2015
Alex Proyas                    2016
Alexander Payne                2013
                               ...
Wes Craven                     2011
Wolfgang Petersen              2006
Woody Allen                    2013
Zack Snyder                    2016
Zhang Yimou                    2014
Name: max, Length: 199, dtype: int64

In [ ]:
data_agg[('year','min')]

director_name
Adam McKay                     2004
Adam Shankman                  2001
Alejandro González Iñárritu    2000
Alex Proyas                    1994
Alexander Payne                1999
                               ...
Wes Craven                     1984
Wolfgang Petersen              1981
Woody Allen                    1977
Zack Snyder                    2004
Zhang Yimou                    2002
Name: (year, min), Length: 199, dtype: int64

In [ ]:
data_agg['title']['count']

director_name
Adam McKay                      6
Adam Shankman                   8
Alejandro González Iñárritu     6
Alex Proyas                     5
Alexander Payne                 5
                               ..
Wes Craven                     10
Wolfgang Petersen               7
Woody Allen                    18
Zack Snyder                     7
Zhang Yimou                     6
Name: count, Length: 199, dtype: int64

In [ ]:
#single level indexing
data_agg.head()

                             year       title
                              min   max count
director_name
Adam McKay                   2004  2015     6
Adam Shankman                2001  2012     8
Alejandro González Iñárritu  2000  2015     6
Alex Proyas                  1994  2016     5
Alexander Payne              1999  2013     5

In [ ]:
data_agg.columns  = ['year_min','year_max','title_count']
data_agg

                             year_min  year_max  title_count
director_name
Adam McKay                       2004      2015            6
Adam Shankman                    2001      2012            8
Alejandro González Iñárritu      2000      2015            6
Alex Proyas                      1994      2016            5
Alexander Payne                  1999      2013            5
...                               ...       ...          ...
Wes Craven                       1984      2011           10
Wolfgang Petersen                1981      2006            7
Woody Allen                      1977      2013           18
Zack Snyder                      2004      2016            7
Zhang Yimou                      2002      2014            6

[199 rows x 3 columns]

In [ ]:
data_agg.reset_index(inplace=True)

In [ ]:
data_agg

                   director_name  year_min  year_max  title_count
0                     Adam McKay      2004      2015            6
1                  Adam Shankman      2001      2012            8
2    Alejandro González Iñárritu      2000      2015            6
3                    Alex Proyas      1994      2016            5
4                Alexander Payne      1999      2013            5
..                           ...       ...       ...          ...
194                   Wes Craven      1984      2011           10
195            Wolfgang Petersen      1981      2006            7
196                  Woody Allen      1977      2013           18
197                  Zack Snyder      2004      2016            7
198                  Zhang Yimou      2002      2014            6

[199 rows x 4 columns]

In [ ]:
data_agg['active_years'] = data_agg['year_max']-data_agg['year_min']
data_agg

,director_name,year_min,year_max,title_count,active_years
0,Adam McKay,2004,2015,6,11
1,Adam Shankman,2001,2012,8,11
2,Alejandro González Iñárritu,2000,2015,6,15
3,Alex Proyas,1994,2016,5,22
4,Alexander Payne,1999,2013,5,14
...,...,...,...,...,...
194,Wes Craven,1984,2011,10,27
195,Wolfgang Petersen,1981,2006,7,25
196,Woody Allen,1977,2013,18,36
197,Zack Snyder,2004,2016,7,12
198,Zhang Yimou,2002,2014,6,12

In [ ]:
data_agg['movies_per_year'] = data_agg['title_count']/data_agg['active_years']
data_agg

,director_name,year_min,year_max,title_count,active_years,movies_per_year
0,Adam McKay,2004,2015,6,11,0.545455
1,Adam Shankman,2001,2012,8,11,0.727273
2,Alejandro González Iñárritu,2000,2015,6,15,0.400000
3,Alex Proyas,1994,2016,5,22,0.227273
4,Alexander Payne,1999,2013,5,14,0.357143
...,...,...,...,...,...,...
194,Wes Craven,1984,2011,10,27,0.370370
195,Wolfgang Petersen,1981,2006,7,25,0.280000
196,Woody Allen,1977,2013,18,36,0.500000
197,Zack Snyder,2004,2016,7,12,0.583333
198,Zhang Yimou,2002,2014,6,12,0.500000

In [ ]:
data_agg.sort_values(by='movies_per_year',ascending=False,inplace=True)

In [ ]:
data_agg

,director_name,year_min,year_max,title_count,active_years,movies_per_year
190,Tyler Perry,2006,2013,9,7,1.285714
73,Jason Friedberg,2006,2010,5,4,1.250000
169,Shawn Levy,2002,2014,11,12,0.916667
158,Robert Rodriguez,1992,2014,16,22,0.727273
1,Adam Shankman,2001,2012,8,11,0.727273
...,...,...,...,...,...,...
104,Lawrence Kasdan,1985,2012,5,27,0.185185
109,Luc Besson,1985,2014,5,29,0.172414
117,Michael Apted,1980,2010,5,30,0.166667
157,Robert Redford,1980,2010,5,30,0.166667
170,Sidney Lumet,1976,2006,5,30,0.166667

In [ ]:
#reset index

In [ ]:
#movies directed by the most profitable directors (atleast one movie directed by him having profit > 200M)

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
#workin gon pfizer dataset => pivot,melting

In [ ]:
import pandas as pd

data = {
    'name': ['Elon', 'Jeff', 'Bill', 'Falguni'],
    'gender': ['M', 'F', 'M', 'F'],
    'income': [53000.0, 28000.0, 25000.0, 44000.0]
}

df = pd.DataFrame(data)
df

      name gender   income
0     Elon      M  53000.0
1     Jeff      F  28000.0
2     Bill      M  25000.0
3  Falguni      F  44000.0

In [ ]:
grouped = df.groupby('gender')
grouped['income'].mean()

gender
F    36000.0
M    39000.0
Name: income, dtype: float64

In [ ]:
grouped.aggregate({'income':['mean']})

         income
           mean
gender
F       36000.0
M       39000.0

In [ ]:
grouped['income'].aggregate('mean')

gender
F    36000.0
M    39000.0
Name: income, dtype: float64